Module7 task1
htmlacademy-ecmascript/1621659-big-trip-14 pull request #12
Opened 2021-05-03 17:49 UTC by tanjaslo

2021-05-04 07:41 UTC, rideorgtfo requested changes
Давай destinations тоже положим в модель?

И комментарии убери пожалуйста.

2021-05-04 07:41 UTC, rideorgtfo commented on src/presenter/board.js
> +    this._sortComponent = new TripSortView(this._currentSortType);
Бесполезное присваивание null. Строкой ниже туда присваивается  TripSortView

2021-05-04 07:41 UTC, rideorgtfo commented on src/presenter/filter.js
> +  }
Этот массив лучше создать не руками, а итерацией по FilterType. Тогда при добавлении новых фильтров не придется менять этот метод

2021-05-04 07:41 UTC, rideorgtfo commented on src/utils/point.js
> +};
Судя по названию даты стоит сравнивать и возвращать boolean?

2021-05-04 07:41 UTC, rideorgtfo commented on src/utils/render.js
> +  }
Этот код нежелателен - может скрыть ошибку. Лучше не вызывать remove там где не надо.

2021-05-04 07:41 UTC, rideorgtfo commented on src/view/edit-form.js
> +  const hasOptions = isArrayEmpty(optionsMap.get(type));
👍

2021-05-04 07:41 UTC, rideorgtfo commented on src/view/edit-form.js
> +          <input class="event__input  event__input--price" id="event-price-1" type="text" name="event-price" type="number" min="0" step="1" value="${he.encode(String(basePrice))}" required>
type может быть только один

2021-05-04 07:41 UTC, rideorgtfo commented on src/view/edit-form.js
> +    if (isNaN(price) || price < 0) {
В evt.target.price лежит строка. Проверки никогда не сработают

2021-05-05 12:55 UTC, rideorgtfo requested changes

2021-05-05 12:55 UTC, rideorgtfo commented on src/model/destinations.js
> +  setFilter(updateType, destinations) {
Почему метод называется setFilter?

2021-05-05 12:55 UTC, rideorgtfo commented on src/presenter/point-new.js
> +import { destinations } from '../mock/destination.js';
Пункты назначения все еще берутся не из модели

2021-05-05 12:57 UTC, rideorgtfo commented
Не все предыдущие замечания исправлены

2021-05-05 13:25 UTC, tanjaslo commented on src/model/destinations.js
> +  setFilter(updateType, destinations) {
опечатка )))

2021-05-06 11:46 UTC, merged