Module2 task1
htmlacademy-ecmascript/1621659-big-trip-14 pull request #4
Opened 2021-04-07 20:55 UTC by tanjaslo

2021-04-08 15:10 UTC, rideorgtfo requested changes

2021-04-08 15:10 UTC, rideorgtfo commented on src/util.js
> +  let days = Math.floor((duration / (1000 * 60 * 60 * 24)) % 30);
DRY

Можно написать так
```
const SECOND = 1000;
const MINUTE = 60 * SECOND;
const HOUR = 60 * MINUTE;
const DAY = 24 * HOUR;

const days = Math.floor(duration / DAY);
const hours = Math.floor(duration / HOUR) - days * DAY;
и так далее
```

Но почему бы тут не использовать dayjs? Как минимум не придется самому делить числа и добавлять leading zero.

2021-04-08 15:10 UTC, rideorgtfo commented on src/util.js
> +  return `${getEventDateFormat(firstPoint.dateFrom)} &mdash; ${getEventDateFormat(lastPoint.dateTo)}`;
DRY

const start =  getEventDateFormat(firstPoint.dateFrom)
const end = startingMonth === endingMonth ? getDayFormat(lastPoint.dateTo) : getEventDateFormat(lastPoint.dateTo)

return `${start} &mdash; ${end}`

2021-04-08 15:10 UTC, rideorgtfo commented on src/view/add-form.js
> +  if (offers.length !== 0) {
Это лишнее, map из пустого массива вернет пустой массив, join породит пустую строку.

2021-04-08 15:10 UTC, rideorgtfo commented on src/view/edit-form.js
> +  if (offers.length !== 0) {
Это не нужно

2021-04-08 15:10 UTC, rideorgtfo commented on src/view/point.js
> +  if (offers.length !== 0) {
И это

2021-04-08 15:10 UTC, rideorgtfo commented on src/view/point.js
> +    const OffersList = offers.map((offer) =>
camelCase

2021-04-08 15:10 UTC, rideorgtfo commented on src/view/point.js
> +  };
Можно вынести эту функцию на верхний уровень, добавив dateFrom и dateTo аргументами

2021-04-09 17:50 UTC, rideorgtfo commented
Нашел фатальный недостаток - нет общего списка всех доступных предложений для типа, только выбранные.
Посмотри макет - там есть не выбранные опции

2021-04-09 18:31 UTC, rideorgtfo requested changes

2021-04-09 18:31 UTC, rideorgtfo commented on src/view/add-form.js
> +  return '';
Лишнее условие

2021-04-12 07:52 UTC, rideorgtfo requested changes

2021-04-12 07:52 UTC, rideorgtfo commented on src/util.js
> +  return unduplicatedPointsNames;
Кстати, тут можно использовать Set для дедубликации.

2021-04-12 07:52 UTC, rideorgtfo commented on src/util.js
> +    return pointsAcc += offers.reduce((offersAcc, offer) => offersAcc + offer.price, 0);
Предлагаю явно поделить присваивание и return.
Первой строчкой +=, второй return

2021-04-12 07:52 UTC, rideorgtfo commented on src/util.js
> +      src: `http://picsum.photos/248/152?r=${(i, i++)}`,
Зачем тут инкремент, если он есть в цикле?

2021-04-12 07:52 UTC, rideorgtfo commented on src/view/add-form.js
> +  const eventTypesList = TYPES.map((type, isChecked) =>
Тут происходит что-то не то. Вторым аргументом приходит индекс элемента в массиве. Как он может означать isChecked?

2021-04-12 10:51 UTC, tanjaslo commented on src/util.js
> +      src: `http://picsum.photos/248/152?r=${(i, i++)}`,
не удалила после удаления getRandomInteger (:

2021-04-12 11:05 UTC, tanjaslo commented on src/view/add-form.js
> +  const eventTypesList = TYPES.map((type, isChecked) =>
тупанула со вторым параметром ) это в принципе снова энтузиазм в целях сокращения количества кода, по заданию не было

2021-04-12 11:15 UTC, tanjaslo commented on src/util.js
> +  return unduplicatedPointsNames;
Я об этом сразу подумала, но нет. Set оставит только уникальные названия из массива, а у нас названия городов повторяться могут, просто не подряд. Т.е., если ивенты в одном городе в течение одной поездки (Novo Mesto - Vrhnika (такси) - Vrhnika (отель) - Vrhnika (экскурсия) - Grosuplje), то Vrhnika будет один раз, но теоретически в Vrhnikу пользователь может вернуться где-то на обратной дороге и она снова будет в маршруте (а с Сетом — нет).

2021-04-12 11:31 UTC, merged